import 'package:get/get.dart';

class EnglishStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'welcome': 'Welcome To Your Space!',
          'submit': 'Submit',
          'maxLimit': 'Maximum Limit is 5',
          'selectLanguage': 'Select Language',
          'language': 'Language',
          'pressEnter': 'Press Enter to Add Tag',
          'edit': 'Edit',
          'error': 'Error',
          'namePlate': 'Choose Name Plate',
          'uploadnamePlate': 'Upload Name Plate',
          'enterPartyName': 'Enter Party Name',
          'addLogo': 'Add Party Logo',
          'addMemberList': 'Add Members List',
          'addMember': 'Add Member',
          'chooseColor': 'Choose Color',
          'uploadLogo': 'Upload Party Logo',
          'addNewParty': 'Add New Party',
          'partyMember': 'Party Member',
          'partyList': 'Party List',
          'viewParty': 'View Party',
          'addParty': 'Add Party',
          'selectRatio': 'Select Ratio for Post',
          'addingCard': 'Adding Card...',
          'yes': 'Yes',
          'no': 'No',
          'deleteCard': 'Are you sure you want to delete this Card?',
          'deleteParty': 'Are you sure you want to delete this Party?',
          'tagAddedSuccessfully': 'Tag Added Successfully!',
          'cardAddedSuccessfully': 'Card Added Successfully!',
          'greetings': 'Greetings',
          'addPost': 'Add Post',
          'addTag': 'Add Tag',
          'tag': 'Tag',
          'tag:': 'Tag :',
          'viewTag': 'View Tag',
          'addTagName': 'Create New Tag',
          'createdGreetingList': 'Created Posts List',
          'enterName': 'Enter Tag Name',
          'download': 'download',
          'share': 'share',
          'tagList': 'Tag Lists',
          'cancel': 'Cancel',
          'newCard': 'Create A New Card',
          'startDate': 'Select Start Date and Time',
          'endDate': 'Select End Date and Time',
          'title': 'Title',
          'login': '-------- Login --------',
          'enterNumber': 'Enter your phone number',
          'enterOtp': 'Enter OTP',
          'otpVerify': 'We will send you a confirmation code',
          'verifyOtp': 'Verify OTP',
          'invalidOtp': 'Invalid OTP',
          'validNumber': 'Enter a valid number',
          'prefixMobile': '+91',
          'continue': 'Continue',
          'uploadPhoto': 'Upload Photo',
          'uploadIcon': 'Upload Icon',
          'update': 'Update',
          'selectAll': 'Please select all fields',
          'sharingContent': 'Sharing Content',
          "noNetMessage":
              "No internet connection was found. Check your connection or try again.",
          "retry": "Retry",
          "netOn": "Connected to Internet!",
          "netOff": "No Internet!",
          "delete": "Delete",
          "addPlate": "Add Plate",
          "deleteAll": "Delete All",
          "setAvatarPosition": "Set Position of Avatar",
          "setPartyLogoPosition": "Set Position of Party Logo",
          "selectAvatarShape": "Select the shape of avatar",
          "selectFontColor": "* Select Font Color :",
          "selectNotifPref": "* Select Notification Preference :",
          "selectNamePlate": "Select Name Plate :",
          "removedNameplate": "Removed Name Plate",
          "background": "Background",
          "uploadBackground": "Upload Background",
          "addBackground": "Background",
          "chooseBackground": "Choose Background",
          "pleaseSelectImage": "Please Select Image!",
          "selectParty": "Select Party",
          "creationTitle": "Create Post",
          "home": "HOME / ",
          "postContent": "Post Content",
          "category": "Category",
          "subCategory": "Sub-Category",
          "addCategory": "Add Category",
          "addSubCategory": "Add Sub-Category",
          "state": "State",
          "selectState": "Select State",
          "uploadPost": "Upload Post",
          "acceptsJpgPng": "Accept only JPEG, PNG.",
          "notificationMessage":
              "Do you like to send a notification to users regarding this post?",
          "wishesMessage": "Set Position For Person Photo",
          "party": "Party",
          'pressEnterCategory': 'Press Enter to Add Category',
          'pressEnterSubCategory': 'Press Enter to Add Sub-Category',
          'pressEnterState': 'Press Enter to Add State',
          "filterByLanguage": "Filter by Language"
        },
      };
}
