import 'package:get/get.dart';

class HindiStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi_IN': {
          'welcome': 'आपका स्वागत है!',
          'submit': 'सबमिट',
          'maxLimit': 'अधिकतम ५ सदस्य जोड़े जा सकते है',
          'viewParty': 'पार्टी देखे',
          'selectLanguage': 'भाषा का टैग चुने ',
          'language': 'भाषा',
          'pressEnter': 'टैग ऐड करने क लिए एंटर दबाए',
          'edit': 'एडिट',
          'addLogo': 'पार्टी का लोगो जोड़े',
          'addMemberList': 'सारे सदस्य जोड़े',
          'addMember': 'सदस्य जोड़े',
          'enterPartyName': 'पार्टी का नाम दर्ज करे',
          'uploadLogo': 'पार्टी का लोगो अपलोड करे',
          'error': 'कुछ गलत हुआ',
          'chooseColor': 'रंग चुने',
          'uploadnamePlate': 'नाम प्लेट अपलोड करे',
          'namePlate': 'नाम प्लेट चुने',
          'addNewParty': 'नया पार्टी जोड़े',
          'partyList': 'पार्टी लिस्ट',
          'partyMember': 'पार्टी सदस्य',
          'addParty': 'पार्टी जोड़े',
          'greetings': 'ग्रीटिंग',
          'addPost': 'पोस्ट जोड़ें',
          'addTag': 'टैग जोड़ें',
          'viewTag': 'टैग देखें',
          'tag': 'टैग',
          'tag:': 'टैग :',
          'addTagName': 'नया टैग जोड़े',
          'enterName': 'टैग का नाम',
          'download': 'डाउनलोड',
          'share': 'साझा',
          'addingCard': 'कार्ड जोड़ा जा रहा है...',
          'tagAddedSuccessfully': 'टैग सफलतापूर्वक जोड़ा गया!',
          'cardAddedSuccessfully': 'कार्ड सफलतापूर्वक जोड़ा गया!',
          'cancel': 'रद्द करे',
          'yes': 'हाँ',
          'no': 'नहीं',
          'selectRatio': 'पोस्ट का रेश्यो चुने',
          'deleteCard': 'क्या आप इस कार्ड को हटाना चाहते हैं?',
          'deleteParty': 'क्या आप इस पार्टी को हटाना चाहते हैं?',
          'tagList': 'टैग सूची',
          'newCard': 'नया पोस्ट बनाएं',
          'startDate': 'आरंभ दिनांक और समय चुनें',
          'endDate': 'अंतिम दिनांक और समय चुनें',
          'title': 'शीर्षक',
          'verifyOtp': 'सत्यापित करें',
          'continue': 'जारी रखें',
          'enterOtp': 'कृपया ओटीपी दर्ज करें',
          'login': '-------- लॉग इन --------',
          'enterNumber': 'अपना फ़ोन नंबर दर्ज करें',
          'otpVerify': 'हम आपको ओटीपी कोड भेजेंगे',
          'validNumber': 'एक वैध नंबर दर्ज करें',
          'invalidOtp': 'अवैध ओटीपी',
          'prefixMobile': '+91',
          'uploadPhoto': 'फोटो अपलोड करें',
          'uploadIcon': 'अपलोड आइकन',
          'createdGreetingList': 'पोस्ट सूची',
          'update': 'अपडेट',
          'selectAll': 'कृपया सभी फ़ील्ड चुनें',
          'sharingContent': 'शेयरिंग कंटेंट',
          "noNetMessage":
              "इंटरनेट कनेक्शन नहीं मिला। अपना कनेक्शन जांचें या फिर से कोशिश करें।",
          "retry": "पुनः प्रयास करें",
          "netOn": "इंटरनेट कनेक्टेड |",
          "netOff": "नो इंटरनेट |",
          "delete": "डिलीट",
          "addPlate": "प्लेट जोड़ें",
          "deleteAll": "डिलीट करें ",
          "setAvatarPosition": "अवतार की पोजीशन चुनें",
          "setPartyLogoPosition": "पार्टी लोगो की पोजीशन चुनें",
          "selectAvatarShape": "* अवतार का अकार चुनें",
          "selectFontColor": "* फ़ॉन्ट का रंग चुनें :",
          "selectNotifPref": "* नोटिफिकेशन :",
          "selectNamePlate": "* नेम प्लेट चुने :",
          "removedNameplate": "नेमप्लेट हटाई गयी",
          "background": "बैकग्राउंड",
          "uploadBackground": "बैकग्राउंड अपलोड करें",
          "addBackground": "बैकग्राउंड जोड़ें",
          "chooseBackground": "बैकग्राउंड जोड़ें",
          "pleaseSelectImage": "कृपया पहले इमेज चुनें!",
          "selectParty": "पार्टी चुनें",
          "creationTitle": "पोस्ट बनायें",
          "home": "होम / ",
          "postContent": "पोस्ट कंटेंट",
          "category": "श्रेणी",
          "subCategory": "उपश्रेणी",
          "addCategory": "श्रेणी चुनें",
          "addSubCategory": "उपश्रेणी चुनें",
          "state": "प्रदेश",
          "selectState": "प्रदेश चुनें",
          "uploadPost": "पोस्ट अपलोड करें",
          "acceptsJpgPng": "केवल JPEG, PNG स्वीकार किए जाते हैं",
          "notificationMessage":
              "क्या आप इस पोस्ट के बारे में उपयोगकर्ताओं को एक अधिसूचना भेजना चाहते हैं?",
          "wishesMessage": "व्यक्ति के फोटो के लिए पोज़िशन निर्धारित करें",
          "party": "पार्टी",
          'pressEnterCategory': 'श्रेणी ऐड करने क लिए एंटर दबाए',
          'pressEnterSubCategory': 'उपश्रेणी ऐड करने क लिए एंटर दबाए',
          'pressEnterState': 'प्रदेश ऐड करने क लिए एंटर दबाए',
          "filterByLanguage": "भाषा द्वारा फ़िल्टर करें"
        },
      };
}
